# Generated by Django 4.0.4 on 2022-06-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='staus',
            field=models.CharField(choices=[('applied', 'applied'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='applied', max_length=120),
        ),
    ]
