# Generated by Django 4.0.4 on 2022-06-15 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_applications_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='staus',
            new_name='status',
        ),
    ]
